apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voise-prometheus-pvc
  namespace: voise
  labels:
    app.kubernetes.io/name: voise-prometheus
    app.kubernetes.io/part-of: voise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
