apiVersion: v1
kind: Service
metadata:
  name: voise-prometheus
  namespace: voise
  labels:
    app.kubernetes.io/name: voise-prometheus
    app.kubernetes.io/part-of: voise
spec:
  selector:
    app: voise-prometheus
  ports:
    - port: 9090
      targetPort: 9090
      name: http
