apiVersion: v1
kind: Service
metadata:
  name: voise-backend
  namespace: voise
  labels:
    app.kubernetes.io/name: voise-backend
    app.kubernetes.io/part-of: voise
spec:
  selector:
    app: voise-backend
  ports:
    - port: 8001
      targetPort: 8001
      name: http
