apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voise-redis-pvc
  namespace: voise
  labels:
    app.kubernetes.io/name: voise-redis
    app.kubernetes.io/part-of: voise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
