apiVersion: v1
kind: Service
metadata:
  name: voise-otel-collector
  namespace: voise
  labels:
    app.kubernetes.io/name: voise-otel-collector
    app.kubernetes.io/part-of: voise
spec:
  selector:
    app: voise-otel-collector
  ports:
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      name: otlp-http
    - port: 8888
      targetPort: 8888
      name: prom-metrics
