apiVersion: v1
kind: Service
metadata:
  name: voise-frontend
  namespace: voise
  labels:
    app.kubernetes.io/name: voise-frontend
    app.kubernetes.io/part-of: voise
spec:
  selector:
    app: voise-frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: http
