"""add canary rollout fields

Revision ID: 06f2fd3811dd
Revises: 4ff201ade0fb
Create Date: 2026-02-05 17:08:56.083060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f2fd3811dd'
down_revision: Union[str, None] = '4ff201ade0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_versions', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('agent_versions', sa.Column('is_canary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_versions', 'is_canary')
    op.drop_column('agent_versions', 'weight')
    # ### end Alembic commands ###
