"""add outcome fields to call log

Revision ID: 0ab4b3fbf2d6
Revises: a8b43a16b68e
Create Date: 2026-02-05 16:17:33.610135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab4b3fbf2d6'
down_revision: Union[str, None] = 'a8b43a16b68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('outcome', sa.String(), nullable=True))
    op.add_column('call_logs', sa.Column('outcome_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'outcome_reason')
    op.drop_column('call_logs', 'outcome')
    # ### end Alembic commands ###
