"""add shadow logs table

Revision ID: 4867a1cc3f39
Revises: 06f2fd3811dd
Create Date: 2026-02-05 17:21:00.296020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4867a1cc3f39'
down_revision: Union[str, None] = '06f2fd3811dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
