"""add memory governance fields

Revision ID: 4c19352af6ef
Revises: 0ab4b3fbf2d6
Create Date: 2026-02-05 16:22:50.532868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c19352af6ef'
down_revision: Union[str, None] = '0ab4b3fbf2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_items', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('memory_items', sa.Column('is_sensitive', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('consent_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'consent_status')
    op.drop_column('memory_items', 'is_sensitive')
    op.drop_column('memory_items', 'expires_at')
    # ### end Alembic commands ###
