"""add multitenancy support

Revision ID: 4ff201ade0fb
Revises: dd51099eecec
Create Date: 2026-02-05 16:31:36.104755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff201ade0fb'
down_revision: Union[str, None] = 'dd51099eecec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.add_column('audit_logs', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.add_column('call_logs', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_call_logs_agent_id'), 'call_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_call_logs_caller_id'), 'call_logs', ['caller_id'], unique=False)
    op.create_index(op.f('ix_call_logs_organization_id'), 'call_logs', ['organization_id'], unique=False)
    op.add_column('conversation_summaries', sa.Column('organization_id', sa.String(), nullable=True))
    op.drop_index('ix_conversation_summaries_agent_id', table_name='conversation_summaries')
    op.create_index(op.f('ix_conversation_summaries_organization_id'), 'conversation_summaries', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'conversation_summaries', 'agents', ['agent_id'], ['id'])
    op.add_column('memory_items', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_memory_items_organization_id'), 'memory_items', ['organization_id'], unique=False)
    op.add_column('pending_actions', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_pending_actions_organization_id'), 'pending_actions', ['organization_id'], unique=False)
    op.add_column('regulatory_policies', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_regulatory_policies_organization_id'), 'regulatory_policies', ['organization_id'], unique=False)
    op.add_column('session_interventions', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_session_interventions_organization_id'), 'session_interventions', ['organization_id'], unique=False)
    op.add_column('user_profiles', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_profiles_organization_id'), 'user_profiles', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_organization_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'organization_id')
    op.drop_index(op.f('ix_session_interventions_organization_id'), table_name='session_interventions')
    op.drop_column('session_interventions', 'organization_id')
    op.drop_index(op.f('ix_regulatory_policies_organization_id'), table_name='regulatory_policies')
    op.drop_column('regulatory_policies', 'organization_id')
    op.drop_index(op.f('ix_pending_actions_organization_id'), table_name='pending_actions')
    op.drop_column('pending_actions', 'organization_id')
    op.drop_index(op.f('ix_memory_items_organization_id'), table_name='memory_items')
    op.drop_column('memory_items', 'organization_id')
    op.drop_constraint(None, 'conversation_summaries', type_='foreignkey')
    op.drop_index(op.f('ix_conversation_summaries_organization_id'), table_name='conversation_summaries')
    op.create_index('ix_conversation_summaries_agent_id', 'conversation_summaries', ['agent_id'], unique=False)
    op.drop_column('conversation_summaries', 'organization_id')
    op.drop_index(op.f('ix_call_logs_organization_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_caller_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_agent_id'), table_name='call_logs')
    op.drop_column('call_logs', 'organization_id')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'organization_id')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_column('agents', 'organization_id')
    # ### end Alembic commands ###
