"""add config column to agent

Revision ID: 65382ff55201
Revises: eb95c281c0d3
Create Date: 2026-02-05 17:39:05.492999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65382ff55201'
down_revision: Union[str, None] = 'eb95c281c0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'config')
    # ### end Alembic commands ###
