"""add_shadow_logs_and_memory_type

Revision ID: 8153ef296d7b
Revises: ba60c51a7af7
Create Date: 2026-02-05 12:40:50.599415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8153ef296d7b'
down_revision: Union[str, None] = 'ba60c51a7af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('primary_model', sa.String(), nullable=True),
    sa.Column('shadow_model', sa.String(), nullable=True),
    sa.Column('primary_response', sa.String(), nullable=True),
    sa.Column('shadow_response', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('intent_match', sa.Boolean(), nullable=True),
    sa.Column('primary_latency_ms', sa.Float(), nullable=True),
    sa.Column('shadow_latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_logs_session_id'), 'shadow_logs', ['session_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('policy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('change_log', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_table('session_interventions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_interventions_session_id'), 'session_interventions', ['session_id'], unique=True)
    op.add_column('agents', sa.Column('active_version_id', sa.String(), nullable=True))
    op.add_column('memory_items', sa.Column('memory_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_items', 'memory_type')
    op.drop_column('agents', 'active_version_id')
    op.drop_index(op.f('ix_session_interventions_session_id'), table_name='session_interventions')
    op.drop_table('session_interventions')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_shadow_logs_session_id'), table_name='shadow_logs')
    op.drop_table('shadow_logs')
    # ### end Alembic commands ###
