"""add goal success criteria and failure conditions

Revision ID: a8b43a16b68e
Revises: 69fe71d69b3b
Create Date: 2026-02-05 16:11:02.397632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b43a16b68e'
down_revision: Union[str, None] = '69fe71d69b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_versions', sa.Column('success_criteria', sa.JSON(), nullable=True))
    op.add_column('agent_versions', sa.Column('failure_conditions', sa.JSON(), nullable=True))
    op.add_column('agent_versions', sa.Column('exit_actions', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('success_criteria', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('failure_conditions', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('exit_actions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'exit_actions')
    op.drop_column('agents', 'failure_conditions')
    op.drop_column('agents', 'success_criteria')
    op.drop_column('agent_versions', 'exit_actions')
    op.drop_column('agent_versions', 'failure_conditions')
    op.drop_column('agent_versions', 'success_criteria')
    # ### end Alembic commands ###
