"""Add agent_knowledge table

Revision ID: da7474f91d36
Revises: 65382ff55201
Create Date: 2026-02-05 18:03:48.066424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'da7474f91d36'
down_revision: Union[str, None] = '65382ff55201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_knowledge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('data_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_knowledge_agent_id'), 'agent_knowledge', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_organization_id'), 'agent_knowledge', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_title'), 'agent_knowledge', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_knowledge_title'), table_name='agent_knowledge')
    op.drop_index(op.f('ix_agent_knowledge_organization_id'), table_name='agent_knowledge')
    op.drop_index(op.f('ix_agent_knowledge_agent_id'), table_name='agent_knowledge')
    op.drop_table('agent_knowledge')
    # ### end Alembic commands ###
