"""add model budget fields

Revision ID: dd51099eecec
Revises: 4c19352af6ef
Create Date: 2026-02-05 16:25:49.723295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd51099eecec'
down_revision: Union[str, None] = '4c19352af6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_versions', sa.Column('token_limit', sa.Integer(), nullable=True))
    op.add_column('agent_versions', sa.Column('fallback_model', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('token_limit', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('fallback_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'fallback_model')
    op.drop_column('agents', 'token_limit')
    op.drop_column('agent_versions', 'fallback_model')
    op.drop_column('agent_versions', 'token_limit')
    # ### end Alembic commands ###
