"""add signature to call logs

Revision ID: e41fb45c8c55
Revises: 4867a1cc3f39
Create Date: 2026-02-05 17:26:58.577634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41fb45c8c55'
down_revision: Union[str, None] = '4867a1cc3f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'signature')
    # ### end Alembic commands ###
