"""add org_id to shadow logs

Revision ID: eb95c281c0d3
Revises: a964561d2d3d
Create Date: 2026-02-05 17:36:36.416298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb95c281c0d3'
down_revision: Union[str, None] = 'a964561d2d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shadow_logs', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_shadow_logs_organization_id'), 'shadow_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_logs_organization_id'), table_name='shadow_logs')
    op.drop_column('shadow_logs', 'organization_id')
    # ### end Alembic commands ###
